upload: False
sources:
  - https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt
  - https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt
  - https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt
  - https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt
  - https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks4.txt
  - https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt
  - https://sunny9577.github.io/proxy-scraper/proxies.txt
  - https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5.txt
  - https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4.txt
  - https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS.txt
  - https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/http.txt
  - https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/socks4.txt
  - https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/socks5.txt
  - https://api.proxyscrape.com/v2/?request=getproxies&protocol=http
  - https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4
  - https://openproxy.space/list/http
  - https://openproxylist.xyz/http.txt
  - https://proxyspace.pro/http.txt
  - https://proxyspace.pro/https.txt
  - https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/http.txt
  - https://raw.githubusercontent.com/andigwandi/free-proxy/main/proxy_list.txt
  - https://raw.githubusercontent.com/Anonym0usWork1221/Free-Proxies/main/proxy_files/http_proxies.txt
  - https://raw.githubusercontent.com/Anonym0usWork1221/Free-Proxies/main/proxy_files/https_proxies.txt
  - https://raw.githubusercontent.com/aslisk/proxyhttps/main/https.txt
  - https://raw.githubusercontent.com/B4RC0DE-TM/proxy-list/main/HTTP.txt
  - https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt
  - https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/http.txt
  - https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/https.txt
  - https://raw.githubusercontent.com/hendrikbgr/Free-Proxy-Repo/master/proxy_list.txt
  - https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt
  - https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-https.txt
  - https://raw.githubusercontent.com/mmpx12/proxy-list/master/http.txt
  - https://raw.githubusercontent.com/mmpx12/proxy-list/master/https.txt
  - https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/http.txt
  - https://raw.githubusercontent.com/NotUnko/autoproxies/main/http.txt
  - https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/http/http.txt
  - https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/https/https.txt
  - https://raw.githubusercontent.com/proxy4parsing/proxy-list/main/http.txt
  - https://raw.githubusercontent.com/proxylist-to/proxy-list/main/http.txt
  - https://raw.githubusercontent.com/prxchk/proxy-list/main/http.txt
  - https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt
  - https://raw.githubusercontent.com/saisuiu/Lionkings-Http-Proxys-Proxies/main/free.txt
  - https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt
  - https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt
  - https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/generated/http_proxies.txt
  - https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt
  - https://raw.githubusercontent.com/TylerAmesIsGay/proxy-list/main/http_proxies%20(2).txt
  - https://raw.githubusercontent.com/TylerAmesIsGay/proxy-list/main/http_proxies%20(3).txt
  - https://raw.githubusercontent.com/yemixzy/proxy-list/main/proxies/http.txt
  - https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/http.txt
  - https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/https.txt
  - https://raw.githubusercontent.com/zevtyardt/proxy-list/main/http.txt
  - https://raw.githubusercontent.com/zloi-user/hideip.me/main/http.txt
  - https://raw.githubusercontent.com/zloi-user/hideip.me/main/https.txt
  - https://rootjazz.com/proxies/proxies.txt
  - https://www.proxy-list.download/api/v1/get?type=http
  - https://www.proxy-list.download/api/v1/get?type=https
  - https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4
  - https://openproxy.space/list/socks4
  - https://openproxylist.xyz/socks4.txt
  - https://proxyspace.pro/socks4.txt
  - https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/socks4.txt
  - https://raw.githubusercontent.com/Anonym0usWork1221/Free-Proxies/main/proxy_files/socks4_proxies.txt
  - https://raw.githubusercontent.com/B4RC0DE-TM/proxy-list/main/SOCKS4.txt
  - https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/socks4.txt
  - https://raw.githubusercontent.com/iptotal/free-proxy-list/master/socks4.txt
  - https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks4.txt
  - https://raw.githubusercontent.com/mmpx12/proxy-list/master/socks4.txt
  - https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/socks4.txt
  - https://raw.githubusercontent.com/NotUnko/autoproxies/main/socks4.txt
  - https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/socks4/socks4.txt
  - https://raw.githubusercontent.com/proxylist-to/proxy-list/main/socks4.txt
  - https://raw.githubusercontent.com/prxchk/proxy-list/main/socks4.txt
  - https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4_RAW.txt
  - https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks4.txt
  - https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/generated/socks4_proxies.txt
  - https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt
  - https://raw.githubusercontent.com/TylerAmesIsGay/proxy-list/main/socks4_proxies%20(1).txt
  - https://raw.githubusercontent.com/yemixzy/proxy-list/main/proxies/socks4.txt
  - https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/socks4.txt
  - https://raw.githubusercontent.com/zevtyardt/proxy-list/main/socks4.txt
  - https://raw.githubusercontent.com/zloi-user/hideip.me/main/socks4.txt
  - https://www.proxy-list.download/api/v1/get?type=socks4
  - https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5
  - https://openproxy.space/list/socks5
  - https://openproxylist.xyz/socks5.txt
  - https://proxyspace.pro/socks5.txt
  - https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/socks5.txt
  - https://raw.githubusercontent.com/Anonym0usWork1221/Free-Proxies/main/proxy_files/socks5_proxies.txt
  - https://raw.githubusercontent.com/B4RC0DE-TM/proxy-list/main/SOCKS5.txt
  - https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/socks5.txt
  - https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt
  - https://raw.githubusercontent.com/iptotal/free-proxy-list/master/socks5.txt
  - https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt
  - https://raw.githubusercontent.com/manuGMG/proxy-365/main/SOCKS5.txt
  - https://raw.githubusercontent.com/mmpx12/proxy-list/master/socks5.txt
  - https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/socks5.txt
  - https://raw.githubusercontent.com/NotUnko/autoproxies/main/socks5.txt
  - https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/socks5/socks5.txt
  - https://raw.githubusercontent.com/proxylist-to/proxy-list/main/socks5.txt
  - https://raw.githubusercontent.com/prxchk/proxy-list/main/socks5.txt
  - https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5_RAW.txt
  - https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks5.txt
  - https://raw.githubusercontent.com/steamboatid/proxyout/main/proxy-socks5.txt
  - https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/generated/socks5_proxies.txt
  - https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt
  - https://raw.githubusercontent.com/TylerAmesIsGay/proxy-list/main/socks5_proxies.txt
  - https://raw.githubusercontent.com/yemixzy/proxy-list/main/proxies/socks5.txt
  - https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/socks5.txt
  - https://raw.githubusercontent.com/zevtyardt/proxy-list/main/socks5.txt
  - https://raw.githubusercontent.com/zloi-user/hideip.me/main/socks5.txt
  - https://www.proxy-list.download/api/v1/get?type=socks5
  - https://free-proxy-list.net/
  - https://proxyscrape.com/free-proxy-list
  - https://proxylist.geonode.com/api/proxy-list?limit=1000&page=1&sort_by=lastChecked&sort_type=desc
  - https://hidemy.io/en/proxy-list/
  - https://hidemy.io/en/proxy-list/?start=64#list
  - https://hidemy.io/en/proxy-list/?start=128#list
  - https://www.freeproxy.world/
  - https://www.freeproxy.world/?type=&anonymity=&country=&speed=&port=&page=2
  - https://www.freeproxy.world/?type=&anonymity=&country=&speed=&port=&page=3
  - https://www.freeproxy.world/?type=&anonymity=&country=&speed=&port=&page=4
  - https://www.freeproxy.world/?type=&anonymity=&country=&speed=&port=&page=5
  - https://www.freeproxy.world/?type=&anonymity=&country=&speed=&port=&page=6
  - https://www.freeproxy.world/?type=&anonymity=&country=&speed=&port=&page=7
  - https://www.freeproxy.world/?type=&anonymity=&country=&speed=&port=&page=8
  - https://www.freeproxy.world/?type=&anonymity=&country=&speed=&port=&page=9
  - https://www.freeproxy.world/?type=&anonymity=&country=&speed=&port=&page=10
  - http://free-proxy.cz/en/
  - http://free-proxy.cz/en/proxylist/main/2
  - http://free-proxy.cz/en/proxylist/main/3
  - http://free-proxy.cz/en/proxylist/main/4
  - http://free-proxy.cz/en/proxylist/main/5
  - http://free-proxy.cz/en/proxylist/main/6
  - http://free-proxy.cz/en/proxylist/main/7
  - http://free-proxy.cz/en/proxylist/main/8
  - http://free-proxy.cz/en/proxylist/main/9
  - http://free-proxy.cz/en/proxylist/main/10
  - https://spys.one/en/
  - https://proxy-list.org/english/index.php
  - https://proxy-list.org/english/index.php?p=2
  - https://proxy-list.org/english/index.php?p=3
  - https://proxy-list.org/english/index.php?p=4
  - https://proxy-list.org/english/index.php?p=5
  - https://proxy-list.org/english/index.php?p=6
  - https://proxy-list.org/english/index.php?p=7
  - https://proxy-list.org/english/index.php?p=8
  - https://proxy-list.org/english/index.php?p=9
  - https://proxy-list.org/english/index.php?p=10
  - https://proxydb.net/
  - https://advanced.name/freeproxy
  - https://advanced.name/freeproxy?page=2
  - https://advanced.name/freeproxy?page=3
  - https://advanced.name/freeproxy?page=4
  - https://advanced.name/freeproxy?page=5
  - https://advanced.name/freeproxy?page=6
  - https://advanced.name/freeproxy?page=7
  - https://advanced.name/freeproxy?page=8
  - https://advanced.name/freeproxy?page=9
  - https://advanced.name/freeproxy?page=10
  - https://scrape-it.cloud/free-proxy-list
  - https://www.proxynova.com/proxy-server-list/country-bd/
  - https://www.proxynova.com/proxy-server-list/country-br/
  - https://www.proxynova.com/proxy-server-list/country-cl/
  - https://www.proxynova.com/proxy-server-list/country-cn/
  - https://www.proxynova.com/proxy-server-list/country-co/
  - https://www.proxynova.com/proxy-server-list/country-fr/
  - https://www.proxynova.com/proxy-server-list/country-de/
  - https://www.proxynova.com/proxy-server-list/country-hk/
  - https://www.proxynova.com/proxy-server-list/country-in/
  - https://www.proxynova.com/proxy-server-list/country-id/
  - https://www.proxynova.com/proxy-server-list/country-jp/
  - https://www.proxynova.com/proxy-server-list/country-ke/
  - https://www.proxynova.com/proxy-server-list/country-nl/
  - https://www.proxynova.com/proxy-server-list/country-pl/
  - https://www.proxynova.com/proxy-server-list/country-ru/
  - https://www.proxynova.com/proxy-server-list/country-rs/
  - https://www.proxynova.com/proxy-server-list/country-kr/
  - https://www.proxynova.com/proxy-server-list/country-tw/
  - https://www.proxynova.com/proxy-server-list/country-th/
  - https://www.proxynova.com/proxy-server-list/country-ua/
  - https://www.proxynova.com/proxy-server-list/country-gb/
  - https://www.proxynova.com/proxy-server-list/country-us/
  - https://www.proxynova.com/proxy-server-list/country-ve/
  - https://www.proxynova.com/proxy-server-list/country-ir/
  - https://www.proxynova.com/proxy-server-list/country-tr/
  - https://www.proxynova.com/proxy-server-list/country-na/
  - https://www.proxynova.com/proxy-server-list/country-mz/
  - https://www.proxynova.com/proxy-server-list/country-it/
  - https://www.proxynova.com/proxy-server-list/country-eg/
  - https://www.proxynova.com/proxy-server-list/country-bg/
  - https://free-proxy-list.net/
  - https://www.socks-proxy.net/
  - https://www.us-proxy.org/
  - https://free-proxy-list.net/uk-proxy.html
  - https://www.sslproxies.org/
  - https://free-proxy-list.net/anonymous-proxy.html
  - https://openproxy.space/list/http
  - https://openproxy.space/list/socks5
  - https://openproxy.space/list/socks4
  - https://www.proxyscan.io/