upload: True
sources:
  - https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt
  - https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt
  - https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt
  - https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt
  - https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks4.txt
  - https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt
  - https://sunny9577.github.io/proxy-scraper/proxies.txt
  - https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5.txt
  - https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4.txt
  - https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS.txt
  - https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/http.txt
  - https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/socks4.txt
  - https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/socks5.txt