on:
  schedule:
    - cron: '25 * * * *'

jobs:
  create_list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: install dependancies
        run: pip3 install -r requirements.txt
      - name: build list
        run: python3 main.py
      - uses: stefanzweifel/git-auto-commit-action@v5

